### ISSUE TITLE
Get a working build for .net full and .net core

### ISSUE THREAD

**Issue by Seeker1437** [Mabiavalon/DockNC#18]

**Comment by wieslawsoltes** [comment]
@Seeker1437 Submit related PR https://github.com/Mabiavalon/DockNC/pull/19

**Comment by Seeker1437** [comment]
Wow you rock, I was literally just looking into doing this. Thanks again!

**Comment by wieslawsoltes** [comment]
I have done this for my projects so it was bit easier.
